### ISSUE TITLE
Installing the Node

### ISSUE THREAD

**Issue by TOSH702** [sumcoinlabs/sumcoin#3]
I keep getting a message when I try and start the rasberry pi.
![Screen Shot 2019-08-01 at 6 00 12 PM](https://user-images.githubusercontent.com/52512037/62336685-4eaba580-b486-11e9-9809-15dfbd8efc64.png)

**Comment by 5053s** [comment]
### Magic block number error.  It may not like your Pi conf's for some reason.

This fixed it for me https://raspberrypi.stackexchange.com/questions/40854/kernel-panic-not-syncing-vfs-unable-to-mount-root-fs-on-unknown-block179-6

Specifically, 
"I had the same problem but with unknown-block(179.7) and the first solution worked fine, just replacing this:

sudo fsck.ext4 -y /dev/mmcblk0p6
with this:

sudo fsck.ext4 -y /dev/mmcblk0p7
"

### Compile yourself option
If all else fails you can compile it yourself in about an hour using this guide
https://github.com/sumcoinlabs/sumcoin/wiki/Build-Your-Own-Raspberry-Pi-Sumcoin-Supernode


Start at dependancies

![image](https://user-images.githubusercontent.com/51257210/62343906-208b8d00-b4a9-11e9-93b5-e3e74d1372b5.png)

**Comment by TOSH702** [comment]
Thank you, I will try it.   
  

  
  

  
  
>

**Comment by sumcoinlabs** [comment]
ARM can be be built this method also.   Investigating the .img to sumcoinNode as it seems to not load on all systems.  Thank you for submitting the issue.

https://github.com/sumcoinlabs/sumcoin/blob/0.16/doc/build-unix.md

![image](https://user-images.githubusercontent.com/37975862/62352489-8128c300-b4c5-11e9-8774-a3c102b1a035.png)

**Comment by TOSH702** [comment]
I have compiled line by line and I have now mounted the img again from a windows computer. I have attached some photos.
![IMG_0366](https://user-images.githubusercontent.com/52512037/62572111-dce9a800-b847-11e9-964d-786d180c0d1f.jpg)
![IMG_0367](https://user-images.githubusercontent.com/52512037/62572112-dce9a800-b847-11e9-8707-272a95560e5c.jpg)
![IMG_0368](https://user-images.githubusercontent.com/52512037/62572113-dce9a800-b847-11e9-9486-bdaa0180a669.jpg)
![IMG_0369](https://user-images.githubusercontent.com/52512037/62572114-dce9a800-b847-11e9-8412-56ad0f6c75eb.jpg)
![IMG_0370](https://user-images.githubusercontent.com/52512037/62572115-dce9a800-b847-11e9-9577-12b4ea1e2565.jpg)
![IMG_0371](https://user-images.githubusercontent.com/52512037/62572116-dce9a800-b847-11e9-803f-170f953575b2.jpg)
![IMG_0372](https://user-images.githubusercontent.com/52512037/62572117-dd823e80-b847-11e9-8803-f7f7d72aed1a.jpg)
![IMG_0373](https://user-images.githubusercontent.com/52512037/62572118-dd823e80-b847-11e9-8bd1-12eab322b5ef.jpg)
