### ISSUE TITLE
Wallet 

### ISSUE THREAD

**Issue by Klin1312** [sumcoinlabs/sumcoin#31]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by Klin1312** [comment]
I want help on POF

**Comment by sumcoinlabs** [comment]
What are you talking about when you say POF??

**Comment by Klin1312** [comment]
I mean how can I switch to sumcoin POS wallet and i have more than 30k coin
on slice wallet, pls help. Thank you

**Comment by sumcoinlabs** [comment]
https://t.me/Sumcoins/22736
