### ISSUE TITLE
CONFIGURE AND RUN Sumcoin

### ISSUE THREAD

**Issue by TOSH702** [sumcoinlabs/sumcoin#4]
I am now getting a message "failed to authenticate". I am in the section: CONFIGURE AND RUN Sumcoin

I have attached a photo. Thank you for your help
![IMG_0364](https://user-images.githubusercontent.com/52512037/62432022-025ca180-b6e2-11e9-8c8e-1b7e9a13e2ef.jpg)

**Comment by CryptoCloudInc** [comment]
> I am now getting a message "failed to authenticate". I am in the section: CONFIGURE AND RUN Sumcoin
> 
> I have attached a photo. Thank you for your help
> ![IMG_0364](https://user-images.githubusercontent.com/52512037/62432022-025ca180-b6e2-11e9-8c8e-1b7e9a13e2ef.jpg)

Would offer you specific help but you haven't attached any build version info or anything.

This assertion is common on newer raspbian distros but should still load if you have all dependancies from the how to guide.   

make sure you have qt deps

```
sudo apt-get install qt4-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev -y;
```
&
```
sudo apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler;
```

Start from the top of the list of dependancies remake, reload, try again.  Sounds like something got missed

**Comment by sumcoinlabs** [comment]
Since this is Pi related, can we please move this issue and create issues in the future at https://github.com/sumcoinlabs/sumnode-pi-os

This will reduce confusion.  Closing this Issue now
