### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by TOSH702** [sumcoinlabs/sumcoin#5]
I have installed it line by line and I have now mounted the img again,
from a windows computer this time. I have attached some photos.

![IMG_0366](https://user-images.githubusercontent.com/52512037/62584231-8476d280-b868-11e9-9cf7-f8d56a94acd9.jpg)
![IMG_0367](https://user-images.githubusercontent.com/52512037/62584232-850f6900-b868-11e9-8ab8-8424b783ea4c.jpg)
![IMG_0368](https://user-images.githubusercontent.com/52512037/62584233-850f6900-b868-11e9-8702-ed41f97bfcaa.jpg)
![IMG_0369](https://user-images.githubusercontent.com/52512037/62584234-850f6900-b868-11e9-89c9-608a1f73f9cc.jpg)
![IMG_0370](https://user-images.githubusercontent.com/52512037/62584235-850f6900-b868-11e9-9d4f-5461c0a8ff14.jpg)
![IMG_0371](https://user-images.githubusercontent.com/52512037/62584236-850f6900-b868-11e9-91b3-a0f28f20e36a.jpg)
![IMG_0372](https://user-images.githubusercontent.com/52512037/62584237-850f6900-b868-11e9-8e15-379997c1a36f.jpg)
![IMG_0373](https://user-images.githubusercontent.com/52512037/62584238-850f6900-b868-11e9-89c5-741d3856fc10.jpg)

**Comment by sumcoinlabs** [comment]
Once again, this has nothing to do with this repo.

Submit your issue on https://github.com/sumcoinlabs/sumnode-pi-os to discuss

**Comment by TOSH702** [comment]
Sorry, I thought I moved it there.
