### ISSUE TITLE
Will not open on MAC

### ISSUE THREAD

**Issue by TOSH702** [sumcoinlabs/sumcoin#6]
I installed the node from your website node it will not open. This is the message I get. I also had to uninstall my antivirus to get it to download. 

This is the error message:
"Process:               Sumcoin-Qt [73009]
Path:                  /Applications/Sumcoin-Qt.app/Contents/MacOS/Sumcoin-Qt
Identifier:            org.sumcoin.Sumcoin-Qt
Version:               0.17.1 (0.17.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sumcoin-Qt [73009]
User ID:               501

Date/Time:             2019-08-15 13:37:20.336 -0700
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Anonymous UUID:        158FA8F9-7F1B-5753-DE31-4BACF1E2A819

Sleep/Wake UUID:       20BF8CCD-48B3-4702-B99A-51B3246B6CBB

Time Awake Since Boot: 480000 seconds
Time Since Wake:       72000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Sumcoin-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10dde4000 -        0x10e81afe7 +org.sumcoin.Sumcoin-Qt (0.17.1 - 0.17.1) <CCE5A3BD-590F-3DBB-9D34-6E737377B762> /Applications/Sumcoin-Qt.app/Contents/MacOS/Sumcoin-Qt
       0x10e912000 -        0x10e912fff +libboost_system.dylib (0) <D1426A1B-2009-390B-832A-A0B3FE7DE72D> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10e917000 -        0x10e926ff7 +libboost_filesystem.dylib (0) <5D6D7A16-7FD6-37A7-B861-8CD71D1BDAF0> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10e933000 -        0x10e940fff +libboost_thread-mt.dylib (0) <59155C51-4CEA-3DC8-9CFF-4BF015C8B118> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10e948000 -        0x10e94cfff +libboost_chrono-mt.dylib (0) <04648B48-A317-343E-B8F2-875AC0BBC732> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10e955000 -        0x10ea5eff7 +QtNetwork (0) <69458827-C341-3A69-8272-C69A5C8EFFD5> /Applications/Sumcoin-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10eaaa000 -        0x10eee7ff7 +QtWidgets (0) <15224A8B-FFD9-382E-8DD8-C8C545C80589> /Applications/Sumcoin-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10f04c000 -        0x10f49eff7 +QtGui (0) <223E45A7-ECDA-3FAB-86C1-3A9CD11FFC9F> /Applications/Sumcoin-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10f5a7000 -        0x10fab3ff7 +QtCore (0) <7B0E915A-26FB-33A1-AB99-4396A27EE8E2> /Applications/Sumcoin-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10fb74000 -        0x10fbd2ff3 +QtDBus (0) <8B69382D-4DDB-395F-89DB-21B61BE1FA5E> /Applications/Sumcoin-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x10fbf2000 -        0x10fbf8ff3 +libqrencode.4.dylib (0) <FE171507-64C1-3743-A10E-C27D02CEC9DE> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x10fc00000 -        0x10fd2fff7 +libprotobuf.18.dylib (0) <21426D21-5A40-3432-AA91-B6E0100FEBDC> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libprotobuf.18.dylib
       0x10fdee000 -        0x10ff02fff +libdb_cxx-4.8.dylib (0) <DB125ECF-171E-3DD9-A1D5-91077E1830ED> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x10ff2a000 -        0x10ff68fff +libssl.1.0.0.dylib (0) <C2EA8DA8-75B7-3FDF-B657-A067B1D5DDBE> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x10ff88000 -        0x1100daf6f +libcrypto.1.0.0.dylib (0) <FB2AAB04-4DC3-382E-9BCE-18DF7DAB8A30> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x110148000 -        0x110150ff7 +libminiupnpc.17.dylib (0) <C4B2F3E3-0CDE-3D69-A33B-450E059ED196> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x110158000 -        0x110159fff +libevent_pthreads-2.1.6.dylib (0) <F500FF7B-6626-3DE9-902B-832A14F8ED5D> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x11015f000 -        0x11018bffb +libevent-2.1.6.dylib (0) <B89316D1-A68F-3827-A8B8-739481584E0E> /Applications/Sumcoin-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x112f2d000 -        0x112f976ef  dyld (655.1.1) <D3E77331-ACE5-349D-A7CC-433D626D4A5B> /usr/lib/dyld
    0x7fff4495c000 -     0x7fff45711ffb  com.apple.AppKit (6.9 - 1671.60.107) <DA722801-0527-3265-ADAE-BB2966649C7C> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff45763000 -     0x7fff45763fff  com.apple.ApplicationServices (50.1 - 50.1) <84097DEB-E2FC-3901-8DD7-A670EA2274E0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff47353000 -     0x7fff47798fff  com.apple.CoreFoundation (6.9 - 1575.17) <57B85682-96F5-3DD9-8969-DF83D07E0295> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff485c6000 -     0x7fff485c6fff  com.apple.CoreServices (946 - 946) <455AB7C9-ECB1-3B5C-8D07-AC68810A90B1> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff495f3000 -     0x7fff499a0fff  com.apple.Foundation (6.9 - 1575.17) <20150BA3-74D6-3991-AD22-52735FAD0E24> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff702ed000 -     0x7fff702eeffb  libSystem.B.dylib (1252.250.1) <E6C586CE-EEFA-3B4B-9316-AC4322AF0E75> /usr/lib/libSystem.B.dylib
    0x7fff705b0000 -     0x7fff70603ff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff70604000 -     0x7fff70619ff7  libc++abi.dylib (400.17) <38C09CED-9090-3719-90F3-04A2749F5428> /usr/lib/libc++abi.dylib
    0x7fff71ba4000 -     0x7fff7232cfd7  libobjc.A.dylib (756.2) <20942D4E-CE6F-376A-8BCD-016F88E4BFD5> /usr/lib/libobjc.A.dylib
    0x7fff73200000 -     0x7fff73204ff3  libcache.dylib (81) <1987D1E1-DB11-3291-B12A-EBD55848E02D> /usr/lib/system/libcache.dylib
    0x7fff73205000 -     0x7fff7320fff3  libcommonCrypto.dylib (60118.250.2) <1765BB6E-6784-3653-B16B-CB839721DC9A> /usr/lib/system/libcommonCrypto.dylib
    0x7fff73210000 -     0x7fff73217ff7  libcompiler_rt.dylib (63.4) <5212BA7B-B7EA-37B4-AF6E-AC4F507EDFB8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff73218000 -     0x7fff73221ff7  libcopyfile.dylib (146.250.1) <98CD00CD-9B91-3B5C-A9DB-842638050FA8> /usr/lib/system/libcopyfile.dylib
    0x7fff73222000 -     0x7fff732a6fc3  libcorecrypto.dylib (602.260.2) <01464D24-570C-3B83-9D18-467769E0FCDD> /usr/lib/system/libcorecrypto.dylib
    0x7fff7332d000 -     0x7fff73366ff7  libdispatch.dylib (1008.270.1) <97273678-E94C-3C8C-89F6-2E2020F4B43B> /usr/lib/system/libdispatch.dylib
    0x7fff73367000 -     0x7fff73393ff7  libdyld.dylib (655.1.1) <002418CC-AD11-3D10-865B-015591D24E6C> /usr/lib/system/libdyld.dylib
    0x7fff73394000 -     0x7fff73394ffb  libkeymgr.dylib (30) <0D0F9CA2-8D5A-3273-8723-59987B5827F2> /usr/lib/system/libkeymgr.dylib
    0x7fff733a2000 -     0x7fff733a2ff7  liblaunch.dylib (1336.261.2) <2B07E27E-D404-3E98-9D28-BCA641E5C479> /usr/lib/system/liblaunch.dylib
    0x7fff733a3000 -     0x7fff733a8fff  libmacho.dylib (927.0.3) <A377D608-77AB-3F6E-90F0-B4F251A5C12F> /usr/lib/system/libmacho.dylib
    0x7fff733a9000 -     0x7fff733abffb  libquarantine.dylib (86.220.1) <6D0BC770-7348-3608-9254-F7FFBD347634> /usr/lib/system/libquarantine.dylib
    0x7fff733ac000 -     0x7fff733adff7  libremovefile.dylib (45.200.2) <9FBEB2FF-EEBE-31BC-BCFC-C71F8D0E99B6> /usr/lib/system/libremovefile.dylib
    0x7fff733ae000 -     0x7fff733c5ff3  libsystem_asl.dylib (356.200.4) <A62A7249-38B8-33FA-9875-F1852590796C> /usr/lib/system/libsystem_asl.dylib
    0x7fff733c6000 -     0x7fff733c6ff7  libsystem_blocks.dylib (73) <A453E8EE-860D-3CED-B5DC-BE54E9DB4348> /usr/lib/system/libsystem_blocks.dylib
    0x7fff733c7000 -     0x7fff7344efff  libsystem_c.dylib (1272.250.1) <7EDACF78-2FA3-35B8-B051-D70475A35117> /usr/lib/system/libsystem_c.dylib
    0x7fff7344f000 -     0x7fff73452ffb  libsystem_configuration.dylib (963.270.3) <2B4A836D-68A4-33E6-8D48-CD4486B03387> /usr/lib/system/libsystem_configuration.dylib
    0x7fff73453000 -     0x7fff73456ff7  libsystem_coreservices.dylib (66) <719F75A4-74C5-3BA6-A09E-0C5A3E5889D7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff73457000 -     0x7fff7345dfff  libsystem_darwin.dylib (1272.250.1) <EC9B39A5-9592-3577-8997-7DC721D20D8C> /usr/lib/system/libsystem_darwin.dylib
    0x7fff7345e000 -     0x7fff73464ff7  libsystem_dnssd.dylib (878.270.2) <E9A5ACCF-E35F-3909-AF0A-2A37CD217276> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff73465000 -     0x7fff734b0ffb  libsystem_info.dylib (517.200.9) <D09D5AE0-2FDC-3A6D-93EC-729F931B1457> /usr/lib/system/libsystem_info.dylib
    0x7fff734b1000 -     0x7fff734d9ff7  libsystem_kernel.dylib (4903.270.47) <4195838C-EFEF-3CC9-B459-75032AF7EA1A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff734da000 -     0x7fff73525ff7  libsystem_m.dylib (3158.200.7) <F19B6DB7-014F-3820-831F-389CCDA06EF6> /usr/lib/system/libsystem_m.dylib
    0x7fff73526000 -     0x7fff73550fff  libsystem_malloc.dylib (166.270.1) <011F3AD0-8E6A-3A89-AE64-6E5F6840F30A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff73551000 -     0x7fff7355bff7  libsystem_networkextension.dylib (767.250.2) <FF06F13A-AEFE-3A27-A073-910EF78AEA36> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff7355c000 -     0x7fff73563fff  libsystem_notify.dylib (172.200.21) <145B5CFC-CF73-33CE-BD3D-E8DDE268FFDE> /usr/lib/system/libsystem_notify.dylib
    0x7fff73564000 -     0x7fff7356dfef  libsystem_platform.dylib (177.270.1) <9D1FE5E4-EB7D-3B3F-A8D1-A96D9CF1348C> /usr/lib/system/libsystem_platform.dylib
    0x7fff7356e000 -     0x7fff73578ff7  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff73579000 -     0x7fff7357cff7  libsystem_sandbox.dylib (851.270.1) <9494594B-5199-3186-82AB-5FF8BED6EE16> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7357d000 -     0x7fff7357fff3  libsystem_secinit.dylib (30.260.2) <EF1EA47B-7B22-35E8-BD9B-F7003DCB96AE> /usr/lib/system/libsystem_secinit.dylib
    0x7fff73580000 -     0x7fff73587ff3  libsystem_symptoms.dylib (820.267.1) <03F1C2DD-0F5A-3D9D-88F6-B26C0F94EB52> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff73588000 -     0x7fff7359dfff  libsystem_trace.dylib (906.260.1) <FC761C3B-5434-3A52-912D-F1B15FAA8EB2> /usr/lib/system/libsystem_trace.dylib
    0x7fff7359f000 -     0x7fff735a4ffb  libunwind.dylib (35.4) <24A97A67-F017-3CFC-B0D0-6BD0224B1336> /usr/lib/system/libunwind.dylib
    0x7fff735a5000 -     0x7fff735d4fff  libxpc.dylib (1336.261.2) <7DEE2300-6D8E-3C00-9C63-E3E80D56B0C4> /usr/lib/system/libxpc.dylib

Model: iMac13,2, BootROM 287.0.0.0.0, 4 processors, Intel Core i7, 3.4 GHz, 16 GB, SMC 2.11f14
Graphics: kHW_NVidiaGeForceGTX675MXItem, NVIDIA GeForce GTX 675MX, spdisplays_pcie_device, 1 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF4), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1325.2)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: ASM1351
USB Device: Wacom Wireless Receiver
Thunderbolt Bus: iMac, Apple Inc., 23.4
"

**Comment by sumcoinlabs** [comment]
Thank you for the logs but can you supply screen shots as well

**Comment by sumcoinlabs** [comment]
The .dmg is not code signed so you will need to open the sumcoin client and then >system preferences>security/privacy> - select "allow anyway" for Sumcoin.

Everything appears to be working.    The issue will remain open for 2 more days unless you have other help needs.

**Comment by sumcoinlabs** [comment]
Use v16 for the time being if you are having issues.

Devs are looking through what the issue is that's causing some users problems 

https://github.com/sumcoinlabs/sumcoin/releases/download/v0.16.1/sumcoin-0.16.1-osx-unsigned.dmg
