### ISSUE TITLE
After MacOS Mojave NO SUMCOIN Wallet on my Desktop :(

### ISSUE THREAD

**Issue by senevrensel** [sumcoinlabs/sumcoin#7]
Hello there , 

Today i upgraded the MacOS to MoJAVE and after that  when i tried to open the desktop wallet of SUMCOIN which i downladed the newest version 3 days ago it did not respond and saying...

**Sumcoin-QT cannot be opened because of a problem.Check with the developer to make sure Sumcoin-Qt works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.**

After that i tried 3 times the same way but the same mistake .

Guys can you pls solve that probem ASAP. I have many coins in my wallet.

Thanks
Kaan

**Comment by sumcoinlabs** [comment]
please revert back to v16 for now https://github.com/sumcoinlabs/sumcoin/releases/download/v0.16.1/sumcoin-0.16.1-osx-unsigned.dmg

**Comment by senevrensel** [comment]
thank you very much for the help. now it is on  :)

**Comment by sumcoinlabs** [comment]
We’ve identified a dependency issue with MAC 17 build where a dependency isn’t communicating correctly for all devices for some reason.   

Until this is resolved, please use branch 16 (which has been made default again) 

17 was tested and believed to be stable prior to release.   Sorry for any stress but thank you for reporting
