### ISSUE TITLE
sumcoin 0.16.1 test-net to 0.16.1 main-net loosing transactions/balance

### ISSUE THREAD

**Issue by vschagen** [sumcoinlabs/sumcoin#8]
When upgrading my sumcoin 0.16.1 test-net to 0.16.1 main-net I can see the wallet but none of the transactions are validated/verified anymore which means I have a "zero" balance.

I didn't use the wallet for a few months, does that mean I am too late and lost my coins?

I am using the precompiles linux binaries. However transferring the wallet.dat to an OSX environment generates the same problem: The wallet is recognised but not validated.

**Comment by 5053s** [comment]
Reading this it isnt clear what your question or problem is

**Comment by vschagen** [comment]
First two screenshots: my old wallet with the transaction confirmations
third screenshot: updated the sumcoin software, it generates an error. This was to be expected since the blockchain from test-net to main-net is different, right?
last two screenshots: finished downloading the new blockchain, it shows my wallet (the same wallet) but the transactions are no longer confirmed, so they dont show up in the balance.

How do I transfer the coins / blockchain? I have another wallet (the one I used to receive the mined coins) with the same problem.

![473142694](https://user-images.githubusercontent.com/27964028/66700324-182bab80-ecbd-11e9-859e-ac99cdb4cb07.jpg)
![1370787046](https://user-images.githubusercontent.com/27964028/66700326-1b269c00-ecbd-11e9-9cdf-80f5ef72bec6.jpg)
![1106789523](https://user-images.githubusercontent.com/27964028/66700327-1cf05f80-ecbd-11e9-93ab-314651795912.jpg)
![1895553730](https://user-images.githubusercontent.com/27964028/66700330-1eba2300-ecbd-11e9-831b-3211bf737747.jpg)
![2107434503](https://user-images.githubusercontent.com/27964028/66700333-21b51380-ecbd-11e9-9565-c09889daad8d.jpg)
